### PR TITLE
compiler host revert

### PR DESCRIPTION
**Pull request by craigmaher**
revert compiler host to net core 2.0 to avoid further conflicts with diag role

### CODE REVIEW

**Comment by puneetg1983** [comment]
You think that the SEV 2 that happened today, (caused by the following exception) was caused due to this change?

`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.Common, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.`

**Comment by craigmaher** [comment]
> eption: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.Common, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

yes I believe it was

**Comment by puneetg1983** [comment]
So even in liberation, compilerhost will use 2.0?

**Comment by puneetg1983** [comment]
> This is a temporary change until we move DaaS over to the liberation project then we can upgrade to net core 3.0.

DaaS is a site extension and it will not be moved to liberation.

**Comment by craigmaher** [comment]
> > This is a temporary change until we move DaaS over to the liberation project then we can upgrade to net core 3.0.
> 
> DaaS is a site extension and it will not be moved to liberation.

I mean until we can deprecate the old Diag role and  all of the detector flows are using the liberation project

**Pull request merged**
