### PR TITLE
Migrating to .NET Core 3.1

### PR DESCRIPTION
**Pull request by rekhaswaminathan**
This PR handles all changes needed to migrate to 3.1

- Program.cs
- Startup.cs
- Nuget package updates
- URL Rewrite changes

Reference - [Migrate to 3.1](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio)

### CODE REVIEW

**Comment by ShekharGupta1988** [comment]
This is great @rekhaswaminathan . 
One idea - Given this is such a critical change, how about we roll this out in staged fashion .How about doing the following:
- Instead of first merging this to main, lets create a branch called 'replat3.1main' or something and keep merging fixes there.
- Deploy couple of endpoints (one euap and one prod) with this branch bits and see if there are more fixes needed. 
- Once we are done, we can merge the 'replat3.1main' branch to 'main'

**Comment by nmallick1** [comment]
I was looking at the Kusto client SDK requirements and I think it does not work with latest .NET Core. 

https://www.nuget.org/packages/Microsoft.Azure.Kusto.Data/

image

**Comment by hforeste** [comment]
> This is great @rekhaswaminathan .
> One idea - Given this is such a critical change, how about we roll this out in staged fashion .How about doing the following:
> 
> * Instead of first merging this to main, lets create a branch called 'replat3.1main' or something and keep merging fixes there.
> * Deploy couple of endpoints (one euap and one prod) with this branch bits and see if there are more fixes needed.  (code, monitoring etc)
> * Once we are done, we can merge the 'replat3.1main' branch to 'main'

Thats a good idea

**Comment by rekhaswaminathan** [comment]
> I was looking at the Kusto client SDK requirements and I think it does not work with latest .NET Core.
> 
> https://www.nuget.org/packages/Microsoft.Azure.Kusto.Data/
> 
> image

Oh really. I ran /dependencyCheck call which Runs heartbeat query and got result. I am also seeing 200 Status code for /rest/query endpoint.

Results - 

image

image

**Comment by hforeste** [comment]
> I was looking at the Kusto client SDK requirements and I think it does not work with latest .NET Core.
> 
> https://www.nuget.org/packages/Microsoft.Azure.Kusto.Data/
> 
> image

I believe we'd just use the .NET Standard libraries

**Comment by rekhaswaminathan** [comment]
> This is great @rekhaswaminathan .
> One idea - Given this is such a critical change, how about we roll this out in staged fashion .How about doing the following:
> 
> * Instead of first merging this to main, lets create a branch called 'replat3.1main' or something and keep merging fixes there.
> * Deploy couple of endpoints (one euap and one prod) with this branch bits and see if there are more fixes needed.  (code, monitoring etc)
> * Once we are done, we can merge the 'replat3.1main' branch to 'main'

You nailed it. ⚡👍

**Review by ShekharGupta1988 — APPROVED** [review]

**Pull request merged**
