### PR TITLE
Upgrade to .net core 2.1

### PR DESCRIPTION
**Pull request by dagrooms52**

### CODE REVIEW

**Comment by dagrooms52** [comment]
Everyone will need to update appsettings.Development.json 
` "CompilerHostBinaryLocation": "...\\src\\Diagnostics.CompilerHost\\bin\\Debug\\netcoreapp2.0",`
to
` "CompilerHostBinaryLocation": "...\\src\\Diagnostics.CompilerHost\\bin\\Debug\\netcoreapp2.1",`

**Comment by dagrooms52** [comment]
Confirmed detector compilation works on 2.1

**Comment by rekhaswaminathan** [comment]
Will this require any changes in DiagnosticRole project because on RoleStart we load and run Runtime host project

**Comment by dagrooms52** [comment]
DiagRole might need a .net core sdk upgrade to the version specified in travis.yml

**Comment by hforeste** [comment]
It might be that diag role is on 2.1 so we'll need to upgrade the sdk to 2.2

**Comment by ShekharGupta1988** [comment]
@dagrooms52  - Can you close this old Pull Request. We are looking to migrate to 2.2 in master2 branch

**Comment by ShekharGupta1988** [comment]
Closing this old PR. Please reopen a new one as necessary.

**Pull request closed without merging**
